baseURL = "https://essenceia.github.io"
languageCode = "en-us"
title = "CatSolution"
themesDir = "themes"
theme = "hugo-hero-theme"
publishDir = "docs"

[params]
  google_analytics_id="UA-134445998-1"

  [params.homepage_meta_tags]
    meta_description = "Cat Solution est une solution inovante et disruptive utilisant des technologies de pointes tel que le FaceID et du machine learning pour reconaitre votre chat"
    meta_og_title = "CatSolution"
    meta_og_type = "website"
    meta_og_url = "https://hugo-hero.netlify.com"
    meta_og_image =""
    meta_og_description = "Parceque votre chat le vaut bien"
    meta_twitter_card = "summary"
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

[[menu.main]]
    name = "Vision"
    url = "/vision/"
    weight = 1

[[menu.main]]
    name = "L'Ã©quipe"
    url = "/work/"
    weight = 2

[[menu.main]]
    name = "Produit"
    url = "/produit/"
    weight = 3



[[menu.main]]
	name = "Etude de marche"
	url = "/etude/"
    weight = 4




[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
